Proxy: Check::DConf Class Reference
Check::DConf Class Reference
#include <Check.h>
Public Member Functions
void Config (const std::string, const std::string)
void * Config (const std::string)
DConf ()
virtual ~DConf ()
Public Member Functions inherited from Check::IConf
virtual void Config (const int, const std::string)
virtual void * Config (const int)
IConf ()
virtual ~IConf ()
Static Public Member Functions
static void SetConfig (const bool _c=true)
static bool GetConfig ()
static void SetReset ()
static bool GetReset ()
Additional Inherited Members
Protected Attributes inherited from Check::IConf
pthread_mutex_t csl
std::shared_ptr< Debug::Debug > logh
Detailed Description
Definition at line 70 of file Check.h.
Constructor & Destructor Documentation
Check::DConf::DConf ()
Definition at line 154 of file Check.cpp.
Check::DConf::~DConf () virtual
Definition at line 180 of file Check.cpp.
Member Function Documentation
void Check::DConf::Config (const std::string _k, const std::string _v) virtual
Implements Check::IConf.
Definition at line 90 of file Check.cpp.
void * Check::DConf::Config (const std::string _k) virtual
Implements Check::IConf.
Definition at line 113 of file Check.cpp.
bool Check::DConf::GetConfig () static
Definition at line 136 of file Check.cpp.
Referenced by Proxy::Nix::Tloop().
bool Check::DConf::GetReset () static
Definition at line 148 of file Check.cpp.
Referenced by Proxy::InnerSocket::Init(), Proxy::StreamClient::Init(), Proxy::StreamServer::Init(), main(), Proxy::Iface::Run(), Proxy::StreamClient::Run(), Proxy::StreamServer::Run(), and Proxy::Nix::Tloop().
void Check::DConf::SetConfig (const bool _c = true) static
Definition at line 130 of file Check.cpp.
void Check::DConf::SetReset () static
Definition at line 142 of file Check.cpp.
Referenced by Check::CConf::CConf(), Proxy::StreamClient::Init(), Proxy::StreamServer::Init(), Proxy::StreamClient::Run(), Proxy::StreamServer::Run(), and sig().
The documentation for this class was generated from the following files:
Check.h
Check.cpp