Proxy: Check::CConf Class Reference
Check::CConf Class Reference
#include <Check.h>
Public Member Functions
void Config (const std::string, const std::string)
void * Config (const std::string)
CConf ()
virtual ~CConf ()
Public Member Functions inherited from Check::IConf
virtual void Config (const int, const std::string)
virtual void * Config (const int)
IConf ()
virtual ~IConf ()
Static Public Member Functions
static void Status (const bool)
static bool Status ()
Additional Inherited Members
Protected Attributes inherited from Check::IConf
pthread_mutex_t csl
std::shared_ptr< Debug::Debug > logh
Detailed Description
Definition at line 89 of file Check.h.
Constructor & Destructor Documentation
Check::CConf::CConf ()
Definition at line 254 of file Check.cpp.
Check::CConf::~CConf () virtual
Definition at line 301 of file Check.cpp.
Member Function Documentation
void Check::CConf::Config (const std::string _k, const std::string _v) virtual
Implements Check::IConf.
Definition at line 185 of file Check.cpp.
void * Check::CConf::Config (const std::string _k) virtual
Implements Check::IConf.
Definition at line 219 of file Check.cpp.
void Check::CConf::Status (const bool _s) static
Definition at line 242 of file Check.cpp.
bool Check::CConf::Status () static
Definition at line 248 of file Check.cpp.
Referenced by Proxy::StreamClient::Init(), Proxy::Iface::Read(), and Proxy::StreamServer::Run().
The documentation for this class was generated from the following files:
Check.h
Check.cpp